<a href="https://colab.research.google.com/github/Abhishek-IITH/Projects/blob/main/Beacon_tracking/Robo_car_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Testdata.csv")
data = df.to_numpy()

In [ ]:
 X = data[:,0:5]
 #print(X.to_string())
 print(X.shape)

(2040, 5)


In [ ]:
Y = data[:,5]
print(Y)

[0 0 0 ... 4 4 4]


In [ ]:
split = 1632
X_train = X[0:split]
Y_train = Y[0:split]
print(X_train)
print(X_train.shape)
print(Y_train)
print(Y_train.shape)

[[-64 -62 -56 -55 -62]
 [-64 -65 -61 -61 -62]
 [-62 -67 -55 -52 -53]
 ...
 [-51 -58 -61 -57 -53]
 [-51 -58 -61 -57 -53]
 [-51 -58 -61 -57 -53]]
(1632, 5)
[0 0 0 ... 4 4 4]
(1632,)


In [ ]:
X_test =  X[split:]
Y_test = Y[split:]
print(X_test)
print(X_test.shape)
print(Y_test)
print(Y_test.shape)

[[-52 -51 -60 -61 -57]
 [-61 -61 -64 -63 -61]
 [-70 -69 -63 -65 -70]
 ...
 [-57 -59 -63 -69 -64]
 [-57 -59 -63 -69 -64]
 [-57 -59 -63 -69 -64]]
(408, 5)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4]
(408,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

k_range = [1,2,3,4,5,6,7,8,9,10]
scores ={}
score_list=[]
#for k in k_range:
knn = KNeighborsClassifier(n_neighbors=12)
knn.fit(X_train, Y_train)
y_pred = knn.predict(X_test)
print(y_pred)
print(Y_test)
scores = metrics.accuracy_score(Y_test,y_pred)
print(scores)
#score_list.append(metrics.accuracy_score(Y_test,y_pred))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 

In [ ]:
ConfusionMatrix = np.zeros([47,47])
TrueLabels=TestLabels.reshape(-1,1)
PredictedLabels = y_pred.reshape(-1,1)
AllLabels=np.hstack((TrueLabels,PredictedLabels))
for i in range(TrueLabels.shape[0]):
  ConfusionMatrix[int(AllLabels[i,0])][int(AllLabels[i,1])]+=1

print("\nConfusion Matrix (check the saved CSV file for details): \n")
print(ConfusionMatrix)
conf_mat = pd.DataFrame(ConfusionMatrix)
conf_mat_file = files_dir+'ConfusionMatrix_'+str(Epochs)+'_'+str(Batch_size)+'_'+str(Number_of_hidden_layers)+'_'+str(Hidden_layer_neurons)+'.csv'
with open(conf_mat_file, mode='w') as f:
    conf_mat.to_csv(f)


In [ ]:
df = pd.read_csv("/content/testpoints (2).csv")
data = df.to_numpy()
X_trial = data[:,0:5]
#print(X.to_string())
print(X_trial.shape)

Y_trial = data[:,5]
print(Y_trial)

(75, 5)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4]


In [ ]:
ytrial_pred = knn.predict(X_trial)
print(ytrial_pred)
print(Y_trial)
scores = metrics.accuracy_score(Y_trial,ytrial_pred)
print(scores)

[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4]
0.4
